site_name: Testbench Runner
repo_name: python_testbench
repo_url: https://github.com/WULPUS/python_testbench

nav:
  - Home: index.md
  - Getting Started:
      - Setup: setup.md
      - Basic Setup: basic_setup.md
  - Configuration: configuration.md
  - Registry:
      - Adding a New Tool: new_tool.md
      - Adding a New File: new_file.md
  - Structure: structure.md

copyright: Copyright &copy; 2025 <a href="mailto:cedr02@live.com">Cedric Hirschi</a>

theme:
  name: material

  font:
    text: Roboto Flex
    code: Roboto Mono

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: black
      accent: amber
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: black
      accent: amber

  icon:
    logo: material/black-mesa
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune
    - toc.follow
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips

plugins:
  - search
  - social
  # - privacy

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.blocks.caption
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
